name: fpg
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - lxml
  - numpy
  - pip
  - pip:
      - quantities
      - elephant
      - rdflib
      - ipython
      - PyYAML
      - neo
      - ipykernel
      - mpi4py
      - tqdm
      - odml
      - scipy
      - ' -e git+ssh://git@github.com/inm-6/reach_to_grasp.git@master#
      egg=r2gtools&subdirectory=python'